# Generated by Django 4.1.8 on 2023-04-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_200_ROWS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=700)),
            ],
        ),
        migrations.DeleteModel(
            name='Drugs',
        ),
    ]
