# Generated by Django 4.2 on 2023-10-02 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_table_200_rows_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_200_rows',
            name='ids',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='table_200_rows',
            name='title',
            field=models.TextField(),
        ),
    ]
