# Generated by Django 4.2 on 2023-10-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_table_200_rows_ids_alter_table_200_rows_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='table_200_ROWS',
            new_name='table',
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['title'], 'verbose_name_plural': 'table'},
        ),
    ]
