# Generated by Django 4.2 on 2023-10-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_rename_table_200_rows_table_alter_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.AlterField(
            model_name='table',
            name='ids',
            field=models.TextField(),
        ),
    ]
