# Generated by Django 4.2 on 2023-10-02 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_alter_table_options_alter_table_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table',
        ),
    ]
