# Generated by Django 4.2 on 2023-10-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0007_delete_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.TextField()),
                ('title_labeler', models.TextField()),
                ('title', models.TextField()),
                ('labeler', models.TextField()),
                ('rxcui', models.IntegerField()),
                ('strentgth', models.TextField()),
                ('query', models.TextField()),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
