# Generated by Django 4.2 on 2023-10-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='strentgth',
            new_name='strength',
        ),
        migrations.AlterField(
            model_name='table',
            name='rxcui',
            field=models.TextField(),
        ),
    ]
