# Generated by Django 4.2 on 2023-10-02 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_rename_strentgth_table_strength_alter_table_rxcui'),
    ]

    operations = [
        migrations.DeleteModel(
            name='table',
        ),
    ]
